export const AuthServiceException = {
  AUTH_USER_EXISTS: 'User with this email exists',
  AUTH_USER_NOT_FOUND: 'User not found',
  AUTH_USER_PASSWORD_WRONG: 'User password is wrong',
};

export const AuthApiResponseDescription = {
  LOGGED_SUCCESS: 'User has been successfully logged.',
  LOGGED_ERROR: 'Password or Login is wrong.',
  USER_FOUND: 'User found',
  USER_NOT_FOUND: 'User not found',
  USER_EXIST: 'User with the email already exists',
  USER_CREATED: 'The new user has been successfully created.',
};
